name: Run Benchmarks

on:
  workflow_dispatch:
    inputs:
      force-run:
        description: "Force run"
        required: false
        default: false
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.head_ref || github.run_id }}-${{ github.workflow }}"
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r requirements-dev.txt

      - name: Run benchmarks
        env:
          FAL_KEY_ID: ${{ secrets.FAL_KEY_ID }}
          FAL_KEY_SECRET: ${{ secrets.FAL_KEY_SECRET }}
          FAL_TARGET_NODE: ${{ secrets.FAL_TARGET_NODE }}
        run: |
          python -m benchmarks artifacts \
            --session-id=latest \
            --target-node=$FAL_TARGET_NODE \
            --iterations=10 \
            --warmup-iterations=3 \
            ${{ fromJSON('["", "--force-run"]')[github.event.inputs.force-run == 'true'] }}

      - name: Regenerate tables
        run: python benchmarks/update_table.py artifacts/latest.json

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "perf: update benchmarks"
          commit_options: "--no-verify"
          commit_user_name: "Fal Bot"
          commit_user_email: "hello@fal.ai"
